export const IMAGES = [
  {
    id: 0,
    title: "Blue Volcano",
    artist: "John Smith",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/blue_volcano.jpg"),
    group: "painting",
    subject: "surrealism",
    medium: "watercolor",
    price: 23840,
    views: 7335,
    date: 3 / 21 / 2021,
  },
  {
    id: 2,
    title: "Galaxy Raccoon",
    artist: "John Smith",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/galaxyraccoon.jpg"),
    group: "digital",
    subject: "animals",
    medium: "",
    price: 47500,
    views: 523,
    date: 3 / 23 / 2021,
  },
  {
    id: 3,
    title: "Geo Room",
    artist: "John Smith",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/geo-room.jpg"),
    group: "digital",
    subject: "abstract",
    medium: "",
    price: 47500,
    views: 700,
    date: 3 / 23 / 2021,
  },
  {
    id: 4,
    title: "Laser Cloud",
    artist: "John Smith",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/laser_cloud.jpg"),
    group: "digital",
    subject: "nature",
    medium: "",
    price: 9764,
    views: 4327648,
    date: 3 / 23 / 2021,
  },
  {
    id: 5,
    title: "Priester Moon",
    artist: "John Smith",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/priester-moon.jpg"),
    group: "digital",
    subject: "landscape",
    medium: "",
    price: 87675,
    views: 28596096,
    date: 3 / 27 / 2021,
  },
  {
    id: 6,
    title: "Pink Eclipse",
    artist: "John Smith",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/priester-pink-eclipse.jpg"),
    group: "digital",
    subject: "landscape",
    medium: "",
    price: 8764,
    views: 3965891,
    date: 3 / 28 / 2021,
  },
  {
    id: 7,
    title: "Priester Tetra",
    artist: "John Smith",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/priester-tetra.jpg"),
    group: "digital",
    subject: "graphicDesign",
    medium: "",
    price: 1358,
    views: 6437642,
    date: 3 / 28 / 2021,
  },
  {
    id: 8,
    title: "Vaporwave in Space",
    artist: "John Smith",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/vaporwave-in-space.jpg"),
    group: "digital",
    subject: "conceptArt",
    medium: "",
    price: 91894,
    views: 238709,
    date: 3 / 29 / 2021,
  },
  {
    id: 21,
    title: "Irony",
    artist: "John Smith",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/ironic-cigarette.jpg"),
    group: "photography",
    subject: "abstract",
    medium: "",
    price: 35436,
    views: 8765484,
    date: 3 / 30 / 2021,
  },
]
