export const IMAGES = [
  {
    id: 0,
    title: "Blue Volcano",
    artist: "John Smith",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/blue_volcano.jpg"),
    group: "painting",
    subject: "surrealism",
    medium: "watercolor",
    price: 23840,
    views: 7335,
    date: 3 / 21 / 2021,
  },
  {
    id: 2,
    title: "Galaxy Raccoon",
    artist: "John Smith",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/galaxyraccoon.jpg"),
    group: "digital",
    subject: "animals",
    medium: "",
    price: 47500,
    views: 523,
    date: 3 / 23 / 2021,
  },
  {
    id: 3,
    title: "Geo Room",
    artist: "John Smith",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/geo-room.jpg"),
    group: "digital",
    subject: "abstract",
    medium: "",
    price: 47500,
    views: 700,
    date: 3 / 23 / 2021,
  },
  {
    id: 4,
    title: "Laser Cloud",
    artist: "John Smith",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/laser_cloud.jpg"),
    group: "digital",
    subject: "nature",
    medium: "",
    price: 9764,
    views: 4327648,
    date: 3 / 23 / 2021,
  },
  {
    id: 5,
    title: "Priester Moon",
    artist: "John Smith",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/priester-moon.jpg"),
    group: "digital",
    subject: "landscape",
    medium: "",
    price: 87675,
    views: 28596096,
    date: 3 / 27 / 2021,
  },
  {
    id: 6,
    title: "Pink Eclipse",
    artist: "John Smith",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/priester-pink-eclipse.jpg"),
    group: "digital",
    subject: "landscape",
    medium: "",
    price: 8764,
    views: 3965891,
    date: 3 / 28 / 2021,
  },
  {
    id: 7,
    title: "Priester Tetra",
    artist: "John Smith",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/priester-tetra.jpg"),
    group: "digital",
    subject: "graphicDesign",
    medium: "",
    price: 1358,
    views: 6437642,
    date: 3 / 28 / 2021,
  },
  {
    id: 8,
    title: "Vaporwave in Space",
    artist: "John Smith",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/vaporwave-in-space.jpg"),
    group: "digital",
    subject: "conceptArt",
    medium: "",
    price: 91894,
    views: 238709,
    date: 3 / 29 / 2021,
  },
  {
    id: 21,
    title: "Irony",
    artist: "John Smith",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/ironic-cigarette.jpg"),
    group: "photography",
    subject: "abstract",
    medium: "",
    price: 35436,
    views: 8765484,
    date: 3 / 30 / 2021,
  },
  {
    id: 22,
    title: "4 Rings",
    artist: "John Smith",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/4-rings.jpg"),
    group: "sculpture",
    subject: "abstract",
    medium: "metal",
    price: 3536,
    views: 8765,
    date: 3 / 29 / 2021,
  },
  {
    id: 23,
    title: "bronze dancer",
    artist: "John Smith",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/bronze-dancer.jpg"),
    group: "sculpture",
    subject: "abstract",
    medium: "metal",
    price: 32536,
    views: 87635,
    date: 3 / 29 / 2021,
  },
  {
    id: 24,
    title: "Surreal Bear",
    artist: "Joram Roukes",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/joram-bear.jpg"),
    group: "painting",
    subject: "surrealism",
    medium: "oil",
    price: 322,
    views: 875,
    date: 5 / 29 / 2021,
  },
  {
    id: 25,
    title: "Joram Skull",
    artist: "Joram Roukes",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/joram-skull.jpg"),
    group: "painting",
    subject: "surrealism",
    medium: "oil",
    price: 1322,
    views: 8275,
    date: 5 / 17 / 2021,
  },
  {
    id: 26,
    title: "Metal Abstract",
    artist: "Anon",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/metal-abstract.jpg"),
    group: "sculpture",
    subject: "abstract",
    medium: "metal",
    price: 13232,
    views: 275,
    date: 7 / 17 / 2021,
  },
  {
    id: 27,
    title: "Faux Clay",
    artist: "Anon",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/metal-bronze.jpg"),
    group: "sculpture",
    subject: "abstract",
    medium: "clay",
    price: 1232,
    views: 2752,
    date: 9 / 7 / 2021,
  },
  {
    id: 28,
    title: "Faux paper bust",
    artist: "Anon",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/metal-bust.jpg"),
    group: "sculpture",
    subject: "abstract",
    medium: "paper",
    price: 1212,
    views: 232,
    date: 1 / 7 / 2021,
  },
  {
    id: 29,
    title: "Metal Man",
    artist: "Anon",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/metal-man.jpg"),
    group: "sculpture",
    subject: "realism",
    medium: "metal",
    price: 712,
    views: 1232,
    date: 1 / 10 / 2021,
  },
  {
    id: 30,
    title: "Abstract Oil",
    artist: "tatum",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/oil-abstract.jpg"),
    group: "painting",
    subject: "abstract",
    medium: "oil",
    price: 4712,
    views: 6232,
    date: 2 / 10 / 2021,
  },
  {
    id: 31,
    title: "Butterfly Lady",
    artist: "tatum",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/oil-butterfly-lady.jpg"),
    group: "painting",
    subject: "contemporary",
    medium: "acrylic",
    price: 4712,
    views: 6232,
    date: 2 / 19 / 2021,
  },
  {
    id: 32,
    title: "Cracked Egg",
    artist: "tatum",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/oil-cracked-egg.jpg"),
    group: "drawing",
    subject: "contemporary",
    medium: "graphite",
    price: 3712,
    views: 8232,
    date: 2 / 21 / 2021,
  },
  {
    id: 33,
    title: "Joram",
    artist: "Joram Roukes",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/oil-joram-roukes.jpg"),
    group: "painting",
    subject: "surrealism",
    medium: "oil",
    price: 912,
    views: 326,
    date: 4 / 21 / 2021,
  },
  {
    id: 34,
    title: "Ocean Sunset",
    artist: "Anon",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/oil-ocean-sunset.jpg"),
    group: "painting",
    subject: "expressionism",
    medium: "oil",
    price: 6612,
    views: 3326,
    date: 4 / 28 / 2021,
  },
  {
    id: 35,
    title: "Underwater Girl",
    artist: "Anon",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/oil-underwater.jpg"),
    group: "photography",
    subject: "portrait",
    medium: "",
    price: 612,
    views: 336,
    date: 4 / 3 / 2021,
  },
  {
    id: 36,
    title: "The Catch",
    artist: "Joram Roukes",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/The-Catch.jpg"),
    group: "painting",
    subject: "surrealism",
    medium: "oil",
    price: 12,
    views: 36,
    date: 6 / 4 / 2021,
  },
  {
    id: 37,
    title: "Adam Riches",
    artist: "adam",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/Adam-Riches.jpg"),
    group: "drawing",
    subject: "realism",
    medium: "graphite",
    price: 12,
    views: 36,
    date: 6 / 4 / 2021,
  },
  {
    id: 38,
    title: "Plant Table",
    artist: "gustavo",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/plant-drawing.jpg"),
    group: "drawing",
    subject: "surrealism",
    medium: "graphite",
    price: 12,
    views: 36,
    date: 6 / 4 / 2021,
  },
  {
    id: 39,
    title: "Stairs Drawing",
    artist: "gustavo",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/stairs-drawing.jpg"),
    group: "drawing",
    subject: "surrealism",
    medium: "graphite",
    price: 12,
    views: 36,
    date: 6 / 4 / 2021,
  },
  {
    id: 40,
    title: "Trippy Drawing",
    artist: "gustavo",
    description:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Similique nesciunt blanditiis, excepturi sit expedita ad delectus corporis necessitatibus commodi consectetur?",
    image: require("../assets/images/trippy-drawing.jpg"),
    group: "drawing",
    subject: "abstract",
    medium: "ink",
    price: 12,
    views: 36,
    date: 6 / 4 / 2021,
  },
]
